# this is a node build
language: node_js

node_js: 16.15.1  # LTS/Gallium

# cache node modules
cache:
  directories:
    - "node_modules"

# make sure to bump the version in package.json before pushing to the artifactory

env:
  global:
    - PROJECT_NAME=@alvch/angular-onscreen-material-keyboard
    # ARTIFACTORY_NPM_USERNAME
    - secure: "Nb5wbVeMYsLhO4A1BaJ94IHIv7mPkLHa+PIxCibSGtuS34ZCEWdZkWb1J7dA/5qfSBnJzItVSRxMwE1poC7zG4lPLgMiRQ3/k/mX1OvDjh/CJsoiCCl+ApYhxwOeUEkLl7XZ4okkWoX7PWCA9eFVfO2OwrIJMOIKsH2r8wb929qzkBvlzVy5V3vpo5z5TxuvMGaNoF2UBqUTPtYLskKLUGIGeCTA36JS8dk+c67c0q6bvr8cyDJULbdSWcv8XAWWJpaAkxkMgdvxi2DmG8JfV5FssSsSQP38nSLgERDTEb+BzlVcGbzwjuB1sUkAcPujk5dxgme+VCKfR2VtrKaraIranHHru2pYNkkRpVQyJz9M7ZJ2JN5OqDztl53oqUWs3CSSWM2D1E5jqGJ8oRWsNLYNTAMr0fWXFQXbYdU4I2fAEMj41Y4jsovQpUyARidtnjS1fgTXzsbgIHCBmmBxmJqbDUvm2UwGfpkAkVD72aOD6zGNeLnq1KMTfehFIE9nhGQAzzx9wy5fUcpDYdZB5hzhsIOmv97zD2aBdb9Qs765NsMnbaelKOvwjFix3pHGCphwL2O7Cjoa8BCihZ2hAdxQvdQf4XtVAOUQqTD2DT/mZ/7yp3eOW3IJcqLRkVitw2V41IyadiW7wRPh3g5I7gh/c+10J/t/36JqH/xPzLk="
    # ARTIFACTORY_NPM_PASSWORD
    - secure: "JTPIPRUHQaAiF3fpbk3TKWTiWrnNuyio+e/VXLNq4jAR+8EqHzlkCOMIRagaxC75WYyczPuTpoOL/FE423uNzrTEfYnR0s9B35APFGshGwbDP5L8k9LhSyHqJ74ySyrho6fB9TaQHUI0JvKsYXaWbSnoKVc6h1K0qBKLzkEkWDxONtddHK16z9Qm5niGbJY4YcJjKx+REkYfO9zB9On/sMB+XCn2POxkaQcXskDoaXFWkHvO7Wf1+vOZ8ZUgO9ECJLV0xGfiQgufEQpfmZHJky7OASI6sEDLjYHqi+76WFWUJ1KO/22bxwqWmx+bqBQdyKcSV2q918G6YpDgEUOHs+o9cBCxktvacQ6CQZIcehOZO2jqBGB1XrWfCYzecydehelwgY89f1JUyL3pseTs/FMugjXhPqxTiYy6HzudOlwudVj2rih2WZwjxl60nvsrzq+1QpniGd9N5qHMiodhPydPMoDzXZgrUjGiocMHLVjtzQWbHJt1JReDYJzCmfbSk7ZAQD51fRflXA+LaGglbXqtNqi84i2MQ7F6PZfoPlV9ao4UbYSqzef9PMbDy/vURs6lnn7slOAkLngx4L2QU4pMtATCV0avpIkEwIf8SOBuYpSk7G7onU9bIn33EbrwdA8jQlCY9NE1tBfLRg+125Byn6wuhL0IRIeuQDBAjjI="
    # ARTIFACTORY_NPM_EMAIL
    - secure: "ULQGU+LCZ6KKtfYSkg5pKCra4MEOsHsZQXdjKz0Z7Jwn1PFiNNExLdpdVkjTjR5QefaP9ycedBsbxCaJfVSG1YyPOKUrBB+qAYSHJsjPGEBbC39QebzTLW+SnvpiThPf8vLsCkbcV19STdhX97HyY+Wzw38h6aPbvUWGQgnS4dnc6VZ0O5KzXoGT6367tFd6EBoFioKee5kwHktOhErIroafJn/3jAWCJyqZKdEiitMXBRd0BETu4CPvnbfyFWKW/HK+UKJ9H4AQs9iHLaRukUvVWPCbfxt/IT4F5ZQ1TaOpxacaCUsyGgraiOwF8TtBFO8Hfvff6aaIirq+WE2Ww5v0eqyHF7pfBHsuPpfyw99cmmlduyf6ln3RxZxd5hPefD3gJqhTWhyhoDYi65OMuKO+biJZuVVAUdwlsEMwE362++f+saDVc+HP9H/WEMdZi+apj7Ydjwd3KcDHvdLqH8m3zSzrfiflMONW1cHa9RSAyAsBpBSSPOhLcbIL0OVYIziLApk3+3gwcqMOP3aeA9o014EqLHjPF+KFvoxeAXfIpCtmS1HJ0W1MFewNBpIQyMIy52b92MIpRmj4vCACWETJNLY4YRq6S6LvHlMrnSACbsIiWBTL7f08YsJ1fJDj7goArHhxrdrfbZRe0AFvht608Cslo4B/aeBtBHPZbjU="
    - NPM_USER=${ARTIFACTORY_NPM_USERNAME}
    - NPM_PASS=${ARTIFACTORY_NPM_PASSWORD}
    - NPM_EMAIL=${ARTIFACTORY_NPM_EMAIL}
    - NPM_REGISTRY=https://alvch.jfrog.io/artifactory/api/npm/alvch/
    - NPM_SCOPE=@alvch

jobs:
  include:
    - stage: build core
      before_script:
        - export EXECUTE_DEPLOY_SCRIPT=$(echo "$TRAVIS_BRANCH" | sed -e "s/^master$\|^release.*$/yes/g")
        - "echo Execute deploy script: $EXECUTE_DEPLOY_SCRIPT"
        - npm config set registry=https://alvch.jfrog.io/artifactory/api/npm/alvch/
        - npm config set @alvch:registry=https://alvch.jfrog.io/artifactory/api/npm/alvch/
        - npm config set //alvch.jfrog.io/artifactory/api/npm/alvch/${ARTIFACTORY_NPM_PASSWORD}
        - npm config set //alvch.jfrog.io/artifactory/api/npm/alvch/${ARTIFACTORY_NPM_USERNAME}
        - npm config set //alvch.jfrog.io/artifactory/api/npm/alvch/${ARTIFACTORY_NPM_EMAIL}
        - npm config set NPM_USER=${ARTIFACTORY_NPM_USERNAME}
        - npm config set NPM_PASS=${ARTIFACTORY_NPM_PASSWORD}
        - npm config set NPM_EMAIL=${ARTIFACTORY_NPM_EMAIL}
        - npm config set NPM_REGISTRY=https://alvch.jfrog.io/artifactory/api/npm/alvch/
        - npm config set NPM_SCOPE=@alvch

      script: true

      deploy:
        - provider: script
          skip_cleanup: true
          script: npm run build && npm run publish
          on:
            all_branches: true
            condition: "$EXECUTE_DEPLOY_SCRIPT = yes"

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
