# this is a node build
language: node_js

node_js: 16.15.1  # LTS/Gallium
python: 3.6

# cache node modules
cache:
  directories:
    - "node_modules"

# make sure to bump the version in package.json before pushing to the artifactory

env:
  global:
    - PROJECT_NAME=@alvch/angular-onscreen-material-keyboard
    # ALVCH_NPM_VIRTUAL_URL
    - secure: "ra1lJrMUYigARx5xeYBU9q/gQmsQm4zq86kP4W6c7NTILmxz/zeKuXgt2WKi0xeWE6qPPGrBhz5+3b/oafNUTKP5aHsJVxqXsJhij26exv/LyL7DrIPhN69v7O2SXtAfV0szgP91qg6SSq6PRVK/C971il/xRZKTrPPpnk0N2v2cYY2rHyEtE3Vih9DDpG4ebV3TJ8zfRLtEz2MXyQBzX0fcyt9cdsuUKgogynlBSxRE8dgrvIKr925dEM1Ar85HjbHga6LwD0KPS5WLtU5OJWOkvPPBbDOE3qya8MTUzmSSdnTt3VBNckhMIo5la4qHjVokl/1Uukf2IRlTWRgiOxRmmZ8vwIx+MOK/QMQy9+ON4A28EF3R0pZA21enTCwpu83/bJB9X3CrDnUMats8VER1fVuhKBEaDfrJMMFk+S677sfu4NH8ZJSWI3QOaTy7WbR5E4iuSGi5i8waKw1FY7cedtfpMrMrpcl+pwYXd507EPIkSFAhPQDJgTjK4Vlor1/R7qVEPhwhmHp0mPlkAEYq6rKbvd/sn27Y4opP9Pt4t7Nof8RUEEDlIH+w5JSU+nCwo2+KkrCgpelJbAGSgFijSrWjHUBng3/K96ijSk3QaCxYBE3CIPNJNiPuf7H4NHmPpJe1+rDH3/fcxiMIfvvz03RfmMZpscXUiPYdBD0="
    # ALVCH_NPM_VIRTUAL_AUTH_TOKEN
    - secure: "UpJOhJ2YBNMw2tZ3uyhw7QmOFzi7zNcKQDsPSCchL9eVpryjIJld370Byr4H6j8j8gHa5VKoITGTHmhT8vzFVxYgwy/MHwJBZ1tQy0TS341yUwd8mqLAGXSoZjpOhHrQdQX8NQFEOXFQ6WzZ+ArfRDmm2HKrh5AyHB3pBc7yxtzdjeOmx2tz5z444D7mD91wuIbpS0AHPcYqx7E+o4vy/aoEOImCBMKVLLZEa7YSfpSrD7qKynebFmoOPu0MxlOC8+xkIWqBcDrTDLYQS6H4SpiActBiPDz6OO7oGyDrTanFwmuRSWklxVssUwNGJKayMRpVdX+D3sCSIK9Ay6StFimmjhNTYx14IRktvzLe2sntAtDABAb19FZ7ouf6ZfPFMBznXd9Zd1T7PX3kmFdrloRe646vQnMzlUmars0GtNRUzlgUHzoG7kTFsccWjYyqgSG76y56NI2JXnqMt16Y/yQyBAmIXKxkfyInMKISilCi4pAhxjNBkLakEymwRyjA15QBfW1v/yXq+gMeRnTBebxxcKXUve4ElvP06PnkL7R9L+TdJVxGNNoGOw8wmNMdp53l57bMtk/QOMmPNeswGRkUU3DRP53WwyB6fBcQeTFTqX3JnTFXW1GHc9YiEoVBazEI5U9LC7Fk4lS0GjggHeGFqB03Q9qgeExDQqkZgtc="
    # ALVCH_NPM_URL
    - secure: "MRZofnuGKKuN1O39QRPzESUivwgoxAcjILaSwaZ083eKjiHtQaBCOVetRAt+n9rJvScjzAvjEZx0STrCuZovDeXCo7aCbCeetJ3+InUph46lwK44wT+BZVGEvYjMo463OiuVsltns1N99INmNI3EI+VK/ialHz2VMBJO/jAZGMh98jEsaWOVP8FzBmiKM4jO4kIvs6xdLMvwW6e/vh2kifSWlEImuwnp7rnm/oZHpCcPCo+6fmphL07QzECdZSegeHALt1KLUMaXvZJW1wUD5i+wAIhkvgPWHloMN5JYOpoVy2ZFZaPPsS+GZlpCjJCafMD/Quw34uPFlXiDcWXvCRuHSQssfAgyo4a81As2QeLKpZx6xjI2/tjh7mnGCAK/Updtr1q9aUJUGQN2ezysILdIUaWs8nYNNofxGNQUtMMcr6TM6TIdmPJR0j3aGXlkM5GyxjwVwzJ9+27W4/y9YjNtH+FJ4+EjLxbKh7zUtM6V5YIvexu64goQDOeupJ5ZzkpYCGRLgmWoDUtC+L5+KZp/PMwlKCSxYzUhUtVR3XoudDV3W5IFvST93botJwLD9XjNYwmDiUPULmcx9j84spOAQtSBRPGvNqF5iTGE0GZvd5ehednHyngJh7a7GFKBOgpp37YaOIlVOw4+Bwv6HB6g+Dt0W38I/s6c7W9cMMA="
    # ALVCH_NPM_AUTH_TOKEN
    - secure: "VMVNOMHY6yAjaZj0kCOE0FXhxHv6u52NuM7QJ2oLEnsCJcQEHdqE0wxMfYfhO6lvJ0LU39tyINPH4zqLh5gshVHcNKf1yh/pHHF/BV+eaOmb51khPDHX5E7heZt6em6lFoSwg/KkYKTAyIkgcLNTIon+KVF/LSFwVwyTmhNwUg8DP/OflHgT2fVXHIQGUwEeNbLukC5s1yx/pZCA7aUSkXEySNwsmzaAf7fvswgKBhTCrRtWK06fpgiqF/54cKgmXmugQdTsl5dvmi5Beh5uJ27VMGAvxtUiFkBdpZTcMaNBuzSi4zycyDgURZwIK57ZxRaI8e5UscAUCXPqxruS0hlgLMdy1QlGTxqED1LBRwiolKtbQqAIiT4eXeg+tjKCb+/iDPGgU+X03IsJo7B+8dvKQa+Ov7W/0xrRj0blEE73aVBmWA5DBJjfaLlHghQIacRIBGdICQ4fe32zUKlRKq0KcYEaMVgeP7pp8Gdh/0TwFm1hWClPAgry6GNjbHzMGc/TgK3Nb6tTJ5yJci9xeUeTWo4ap+d9S8NwpgMcYxCwlk9IXk1XMzfYx/s/eErfHeUWI30fuQpnorGW2Z0euuWxRkvnBDz+9RQdpqF5pGWyYijrhqFgfrpWiBrP9xTKli087J/kgxzCQUbeXA9Xuns90hoDavGQYheGmsRGraE="
before_install:
  - export EXECUTE_DEPLOY_SCRIPT=$(echo "$TRAVIS_BRANCH" | sed -e "s/^master$\|^release.*$/yes/g")
  - "echo Execute deploy script: $EXECUTE_DEPLOY_SCRIPT"
  - npm config set registry=https:${ALVCH_NPM_VIRTUAL_URL}
  - npm config set ${ALVCH_NPM_VIRTUAL_URL}:_auth=${ALVCH_NPM_VIRTUAL_AUTH_TOKEN}
  - npm config set @alvch:registry=https:${ALVCH_NPM_URL}
  - npm config set ${ALVCH_NPM_URL}:_auth=${ALVCH_NPM_AUTH_TOKEN}
  - npm config set ${ALVCH_NPM_URL}:always-auth=true
script: npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run build && npm run publish
    on:
      all_branches: true
      condition: "$EXECUTE_DEPLOY_SCRIPT = yes"
addons:
  apt:
    packages:
      - g++

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
